version: '3'

services:
  consul:
    image: consul
    ports:
      - "8500:8500"
    tmpfs:
      - /consul/data
    volumes:
      - ./consul-config:/consul/config
    networks:
      - n1

networks:
  n1:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16